name = "land"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "land.xcpvip.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.land.xcpvip.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.land.xcpvip.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.land.xcpvip.dpdns.org", custom_domain = true },
  { pattern = "info.microsoft.com.land.xcpvip.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.land.xcpvip.dpdns.org", custom_domain = true },  
  { pattern = "quiz.int.vidio.com.land.xcpvip.dpdns.org", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "3be3a2fdebff4c4aad5fbb4c4d8e79df"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "7265646d-6933-4300-9abc-41e2edba3777"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/Koelpin47/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/Koelpin47/Siren/refs/heads/master/web/sub.html"
